[tools]
actionlint = "1.7.10"
ginkgo = '2.25.2'
golang = '1.24'
golangci-lint = "2.8.0"
"go:golang.org/x/tools/cmd/goimports" = "0.41.0"
'go:fybrik.io/crdoc' = 'latest'
helm = "4.1"
helm-ct = "3.14.0"
helm-docs = "1.14.2"
kube-controller-tools = "0.20.0"
kubectl = "1.35"
kustomize = "5.8.0"
pre-commit = "4.5.1"
setup-envtest = "0.23.1"
shellcheck = "0.11.0"
yamllint = "1.38.0"
yq = "4.52.2"
go = "1.25"

[settings]
experimental = true
