[tools]
actionlint = "1.7.9"
ginkgo = '2.25.2'
golang = '1.24'
golangci-lint = "2.6.2"
"go:golang.org/x/tools/cmd/goimports" = "0.39.0"
'go:fybrik.io/crdoc' = 'latest'
helm = "3.19"
helm-ct = "3.14.0"
helm-docs = "1.14.2"
kube-controller-tools = "0.19.0"
kubectl = "1.34"
kustomize = "5.8.0"
pre-commit = "4.5.0"
setup-envtest = "0.22.4"
shellcheck = "0.11.0"
yamllint = "1.37.1"
yq = "4.49.2"
go = "1.25"

[settings]
experimental = true
